name: hakangulgonul_test
favicon: null
layout_spectrum: 0.18596643558703363
typography_spectrum: 0.02372807334177196
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.8564984742552042
  lightness: 0.5408530454151332
  saturation: 0.7210753231775016
  rhythmicContrast: 0.028916657902300358
purpose: []
